-- Seed: all 50 US states
-- Run after 001_create_tables.sql

insert into states (name, slug, abbreviation, secretary_of_state_url) values
('Alabama', 'alabama', 'AL', 'https://www.sos.alabama.gov'),
('Alaska', 'alaska', 'AK', 'https://www.commerce.alaska.gov'),
('Arizona', 'arizona', 'AZ', 'https://azsos.gov'),
('Arkansas', 'arkansas', 'AR', 'https://www.sos.arkansas.gov'),
('California', 'california', 'CA', 'https://www.sos.ca.gov'),
('Colorado', 'colorado', 'CO', 'https://www.sos.state.co.us'),
('Connecticut', 'connecticut', 'CT', 'https://portal.ct.gov/sots'),
('Delaware', 'delaware', 'DE', 'https://corp.delaware.gov'),
('Florida', 'florida', 'FL', 'https://dos.fl.gov'),
('Georgia', 'georgia', 'GA', 'https://sos.ga.gov'),
('Hawaii', 'hawaii', 'HI', 'https://cca.hawaii.gov'),
('Idaho', 'idaho', 'ID', 'https://sos.idaho.gov'),
('Illinois', 'illinois', 'IL', 'https://www.ilsos.gov'),
('Indiana', 'indiana', 'IN', 'https://www.in.gov/sos'),
('Iowa', 'iowa', 'IA', 'https://sos.iowa.gov'),
('Kansas', 'kansas', 'KS', 'https://www.sos.ks.gov'),
('Kentucky', 'kentucky', 'KY', 'https://www.sos.ky.gov'),
('Louisiana', 'louisiana', 'LA', 'https://www.sos.la.gov'),
('Maine', 'maine', 'ME', 'https://www.maine.gov/sos'),
('Maryland', 'maryland', 'MD', 'https://sos.maryland.gov'),
('Massachusetts', 'massachusetts', 'MA', 'https://www.sec.state.ma.us'),
('Michigan', 'michigan', 'MI', 'https://www.michigan.gov/sos'),
('Minnesota', 'minnesota', 'MN', 'https://www.sos.state.mn.us'),
('Mississippi', 'mississippi', 'MS', 'https://www.sos.ms.gov'),
('Missouri', 'missouri', 'MO', 'https://www.sos.mo.gov'),
('Montana', 'montana', 'MT', 'https://sosmt.gov'),
('Nebraska', 'nebraska', 'NE', 'https://sos.nebraska.gov'),
('Nevada', 'nevada', 'NV', 'https://www.nvsos.gov'),
('New Hampshire', 'new-hampshire', 'NH', 'https://www.sos.nh.gov'),
('New Jersey', 'new-jersey', 'NJ', 'https://www.njconsumeraffairs.gov'),
('New Mexico', 'new-mexico', 'NM', 'https://www.sos.nm.gov'),
('New York', 'new-york', 'NY', 'https://www.dos.ny.gov'),
('North Carolina', 'north-carolina', 'NC', 'https://www.sosnc.gov'),
('North Dakota', 'north-dakota', 'ND', 'https://sos.nd.gov'),
('Ohio', 'ohio', 'OH', 'https://www.ohiosos.gov'),
('Oklahoma', 'oklahoma', 'OK', 'https://www.sos.ok.gov'),
('Oregon', 'oregon', 'OR', 'https://sos.oregon.gov'),
('Pennsylvania', 'pennsylvania', 'PA', 'https://www.dos.pa.gov'),
('Rhode Island', 'rhode-island', 'RI', 'https://www.sos.ri.gov'),
('South Carolina', 'south-carolina', 'SC', 'https://www.scsos.com'),
('South Dakota', 'south-dakota', 'SD', 'https://sdsos.gov'),
('Tennessee', 'tennessee', 'TN', 'https://sos.tn.gov'),
('Texas', 'texas', 'TX', 'https://www.sos.state.tx.us'),
('Utah', 'utah', 'UT', 'https://corporations.utah.gov'),
('Vermont', 'vermont', 'VT', 'https://sos.vermont.gov'),
('Virginia', 'virginia', 'VA', 'https://www.scc.virginia.gov'),
('Washington', 'washington', 'WA', 'https://www.sos.wa.gov'),
('West Virginia', 'west-virginia', 'WV', 'https://sos.wv.gov'),
('Wisconsin', 'wisconsin', 'WI', 'https://www.sos.state.wi.us'),
('Wyoming', 'wyoming', 'WY', 'https://sos.wyo.gov')
on conflict (slug) do nothing;
